---
title: Will Anderson
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  works:
    title: Works
    output: true
    permalink: "/work/:path/"
defaults:
- scope:
    path: ""
    type: "works"
  values:
    name:
    layout: work
    source: http://google.com
    thumbnail_path:
    bg-image:
    images:
    - path:
      caption:
      cols: ["6", "12"]
      class: ["desktop", "mobile", "video"]
    credits:
      - job:
        name:
    press:
      - pub:
        url:
url: http://willanderson.co
show_drafts: true
