---
title: Will Anderson
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  works:
    title: Works
    output: true
    permalink: "/work/:path/"
defaults:
- scope:
    path: ''
    type: works
  values:
    name:
    featured: false
    layout: work
    source: http://google.com
    thumbnail_path:
    bg-image:
    images:
    - path:
      caption:
      narrow: false
      addpadding: false
    credits:
    - job:
      name:
      url:
    press:
    - pub:
      url:
url: http://willanderson.co
show_drafts: true
